version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

